/*
    3) FAÇA UM PROGRAMA QUE CALCULE E IMPRIMA O SALARIO A SER TRANSFERIDO PARA UM FUNCUIONARIO
    
    PARA REALIZAR O CALCULO RECEBA O VALOR BRUTO DO SALRIO E O ADICIONAL DOS BENEFICIOS
    O SALARIO 
*/


const { gets, print } = require('./funcao-ex3');